server.port=9310

spring.application.name=gateway

spring.cloud.gateway.server.webmvc.routes[0].id=produk-service
spring.cloud.gateway.server.webmvc.routes[0].uri=lb://PRODUK
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/api/produk/**

spring.cloud.gateway.server.webmvc.routes[1].id=order-service
spring.cloud.gateway.server.webmvc.routes[1].uri=lb://ORDER
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/api/order/**

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://172.18.0.2:8761/eureka/
eureka.instance.hostname=localhost
