input {
  tcp {
    port => 5000
    codec => json
  }
}

filter {
  mutate {
    add_field => { "[@metadata][target_index]" => "microservice-%{+YYYY.MM.dd}" }
  }

  if [event_type] == "user_activity" {
    mutate {
      replace => { "[@metadata][target_index]" => "user-activity-%{+YYYY.MM.dd}" }
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "%{[@metadata][target_index]}"
  }

}
